### PR TITLE
Fix custom XPath function addition

### PR DESCRIPTION
**Pull request by alxndrsn**

### CODE REVIEW

**Comment by MartijnR** [comment]
👍  I'll test this with the custom functions we're using (with OpenClinica), and will get back shortly!

**Comment by MartijnR** [comment]
Hi Alex,

I updated the branch at enketo-xpath-extensions-oc, and it's not yet working: https://github.com/OpenClinica/enketo-xpath-extensions-oc/blob/fix/new-xpath-evaluator/src/custom-functions.js#L72

I think it's because you're adding the functionality to an instance of the evaluator, and enketo-XPathJS adds it to the prototype (actually not sure if prototype is the right word in the case of XPathJS).

So `ORXE.customXPathFunction.add( ....)` instead of `evaluator.customXPathFunction.add(...)` should make it compatible.

**Comment by alxndrsn** [comment]
I've made them run at https://github.com/OpenClinica/enketo-xpath-extensions-oc/pull/3

Some differences:

* the referenced commit for openrosa-xpath-evaluator was not from the PR at https://github.com/alxndrsn/openrosa-xpath-evaluator/tree/custom-functions
* how the evaluator is initialised/how custom functions are bound (as you noted)
* argument and return type conversion are now handled automatically, so don't need to be done in `custom-functions.js` (see `NEW_ORXE` conditionals).  This is as discussed at https://github.com/medic/openrosa-xpath-evaluator/issues/60
* I seem to have messed up the node-forge dependency in https://github.com/alxndrsn/openrosa-xpath-evaluator/tree/implement-predicates, and consequently https://github.com/alxndrsn/openrosa-xpath-evaluator/tree/custom-functions; I'll fix this!
* the error messages in ORXE2 are different from the current ones, so 4 tests are currently failing.  Would you like the new implementation to match existing error messages?

**Comment by MartijnR** [comment]
Thanks Alex, there seems to have been some odd GitHub issue in which my last (Nov 23) commits were temporarily not visible to you. Explains the merge conflict as well. I'll have a look today!

**Comment by MartijnR** [comment]
I think this should work (in Enketo Core as well). 👍 

> the error messages in ORXE2 are different from the current ones, so 4 tests are currently failing. Would you like the new implementation to match existing error messages?

Your messages are nicer! The only thing that would be great to add is the function name. Like "Function "pad2" expects 1 arg(s), but got 2". Makes it easier for form designers to troubleshoot complex expressions with multiple function calls.

**Comment by alxndrsn** [comment]
> The only thing that would be great to add is the function name.

:+1: This is now done, on https://github.com/medic/openrosa-xpath-evaluator/pull/61

**Pull request closed without merging**
